### PR TITLE
Saveloads in frame bulks and fix to afterframes resuming too late.

### LINKED ISSUE #91: [Request] Add support for recording demos through s/l
Currently there is no easy way to record demos through save-loads in a single script. It seems that the current recording mechanism is just using the record command, which stops as soon as you save-load. The only way to go recording demos like this atm is by using speedrun_segment which doesn't keep the same demo name as at the top of the script, or by doing some janky jankyness with y_spt_pause 2.

### LINKED ISSUE #96: _y_spt_afterframes_await_load resumes 1 tick after the game loads

### PR DESCRIPTION
**Pull request by Jukspa**
Fixes #96 and fixes #91.

### CODE REVIEW

**Comment by YaLTeR** [comment]
Any tests for this?

**Comment by Jukspa** [comment]
For the saveloads or afterframes resuming earlier?

**Comment by YaLTeR** [comment]
Both, if possible, I guess?

**Comment by Jukspa** [comment]
Gonna add a check so that the sl bulk doesnt overwrite the original save.

**Comment by YaLTeR** [comment]
Thanks

**Pull request merged**
