### PR TITLE
improve bms version detecting

### PR DESCRIPTION
**Pull request by tmob03**

### CODE REVIEW

**Comment by tmob03** [comment]
what why is oe failing the error is in not in a compiled in part

**Comment by tmob03** [comment]
whatever

**Comment by lipsanen** [comment]
is there a problem with version detection? In general I think spt has too many ifdefs already

**Comment by tmob03** [comment]
Smaller DLL size is what I was going for. As for the BMS changes, I changed those because Mod and current release were calling the function for 0.9 detection

**Comment by lipsanen** [comment]
I would prefer no added ifdefs. The BMS functions are kinda weirdly named, you would think DoesGameLookLikeBMS would match all versions but it doesnt

**Comment by lipsanen** [comment]
tyvm

**Pull request merged**
