### PR TITLE
Added y_spt_dev_cvars

### PR DESCRIPTION
**Pull request by evanlin96069**
- `y_spt_dev_cvars` Prints all developer/hidden CVars.
- Added autocomplete for `y_spt_cvar` and `y_spt_cvar2`

### CODE REVIEW

**Comment by lipsanen** [comment]
Is the steampipe autocomplete issue fixed yet?

**Comment by evanlin96069** [comment]
> Is the steampipe autocomplete issue fixed yet?

No, I did some testing with simpler autocomplete functions but the game still crashed. Not sure why...

**Comment by lipsanen** [comment]
can you remove the autocompletion stuff from steampipe so it doesnt crash

**Comment by evanlin96069** [comment]
> can you remove the autocompletion stuff from steampipe so it doesnt crash

Steampipe doesn't have autocompletion already.
Steampipe autocompletion macros removed in 1fddf34452533133fc36349a596ecc29beb0a5ba.
Other autocompletion for `y_spt_cam_path_rmkf`, `y_spt_cvar`, and `y_spt_cvar2` also have `#ifdef SSDK2013`.
But I still removed all autocompletion implementation completely just to make sure.

**Comment by lipsanen** [comment]
gotcha

**Comment by lipsanen** [comment]
thanks

**Pull request merged**
