### PR TITLE
Fix y_spt_additional_jumpboost and Add y_spt_aircontrol

### PR DESCRIPTION
**Pull request by evanlin96069**
- Fix y_spt_additional_jumpboost using 2838's implementation.
- Add FCVAR_DEMO flag to y_spt_autojump.
- Change the incorrect pattern label in FinishGravity.
- Add y_spt_aircontrol for Portal.

### CODE REVIEW

**Comment by InputEvelution** [comment]
What exactly is "HL2DM movement mechanic" supposed to be about? I'm aware that autojump doesn't seem to work properly in that game, but I don't think the player ever gets a horizontal boost upon jumping.

**Comment by evanlin96069** [comment]
> What exactly is "HL2DM movement mechanic" supposed to be about? I'm aware that autojump doesn't seem to work properly in that game, but I don't think the player ever gets a horizontal boost upon jumping.

tbh, I'm not sure if that's HL2DM movement mechanic because I didn't play HL2DM before... It's the movement you got if you set `maxplayers` > 1 in Portal or HL2. Basically, no jump boost, you can bhop.

**Comment by lipsanen** [comment]
thanks

**Comment by lipsanen** [comment]
> It may also be worth removing the additional_ from the command's name as well.
There was some discussion about the entire naming scheme in spt and I think most people agreed that it should only be spt_*, ie. drop the leading _y and y_. I probably would still want to mirror the old cvars so that they work by their old names, afaik that should be possible.

**Pull request merged**
