### PR TITLE
_y_spt_force_fov

### PR DESCRIPTION
**Pull request by Margen67**
Allows setting the FOV to values aside from 90.

### CODE REVIEW

**Comment by YaLTeR** [comment]
Requesting approval from @Jukspa, also maybe the leading `_` can be dropped.

**Comment by SmileyAG** [comment]
Oh yeah, maybe its also worth to add in this PR support `_y_spt_force_fov` for OrangeBox?

I remember yookspa said that was based on overlay code,

**Review by lipsanen — APPROVED** [review]
seems fine to me

**Comment by YaLTeR** [comment]
Thanks!

**Pull request merged**
